import { Injectable } from '@angular/core';
import { Router } from '@angular/router';
import { FormControl, Validators } from '@angular/forms';

import {Clipboard} from '@angular/cdk/clipboard';

@Injectable({
  providedIn: 'root'
})
export class ResourceService {

  cartList = [
    {id:'price_1LuTMaENE7uabJh2F2h4YBiO', name:"Startup Community", way:"79 First Year then $99", price:99, cost:79,  
    priceINR:8204, costINR:6549,  
    priceEUR:102, costEUR:82, 
    priceUSD:99, costUSD:79,
    priceRUB:5956, costRUB:4753,
    during:"1 Year", days:365 },
    {id:'price_1LuTPKENE7uabJh2rrXnRV5u', name:"Pledged Community", way:"33/year Pledged for 3 Years", price:297, cost:99, 
    priceINR:24623, costINR:8204, 
    priceEUR:305, costEUR:102, 
    priceUSD:297, costUSD:99, 
    priceRUB:17867, costRUB:5956,
    during:"3 Year", days:(365*3) },
    {id:'price_1LuTQrENE7uabJh2aYyTOtfT', name:"Prepaid Enterprise", way:"49/month Prepaid Subscription", price:49, cost:49, 
    priceINR:4003, costINR:4003, 
    priceEUR:48, costEUR:48, 
    priceUSD:49, costUSD:49, 
    priceRUB:2948, costRUB:2948,
    during:"Monthly", days:30 },
  ]
  
  videoEducation = "assets/videos/education.mp4";
  videoBusiness = "assets/videos/business.mp4";

  videoOpensourceIcons = "assets/videos/video_icons.mp4";
  videoOpensourceMaps = "assets/videos/video_maps.mp4";
  videoOpensourceDatasets = "assets/videos/video_datasets.mp4";
  videoOpensourceFonts = "assets/videos/video_fonts.mp4";
  videoOpensourceModels = "";
  videoOpensourceImages = "";
  videoOpensourceVideos = "";
  videoOpensourceTracks = "";
  videoOpensourcePalettes = "assets/videos/video_palettes.mp4";
  videoOpensourceGradients = "assets/videos/video_gradients.mp4";
  videoOpensourcePatterns = "assets/videos/video_patterns.mp4";
  videoOpensourceShades = "assets/videos/video_shades.mp4";

  xLang = "ENG"
  xArea = "US"
  xCoin = "USD"
  bgInvert = false; // icon
  modeBgFc = true; // icon
  bgColor = ""; // icon
  fgColor = ""; // icon
  scaleMapX = 1; // map
  moveMapUD = 0; // map
  moveMapLR = 0; // map
  
  navOpensource = [
    {count:3000, about:"svg png webp with 24:24 viewbox", icon:"shape_line", name:"Icons",path:"/icons"},
    {count:214, about:"svg jpeg png webp with editor", icon:"map", name:"Maps",path:"/maps"},
    {count:9999, about:"json xml csv documents", icon:"data_object", name:"Datasets",path:"/datasets"},
    {count:1442, about:"Library of regional font scripts", icon:"font_download", name:"Fonts",path:"/fonts"},
    // {count:0, about:"3D stock graphics", icon:"vrpano", name:"Models",path:"/models"},
    // {count:0, about:"HD stock pictures", icon:"photo_album", name:"Images",path:"/images"},
    // {count:0, about:"4K stock footages", icon:"movie_creation", name:"Videos",path:"/videos"},
    // {count:0, about:"HR stock sounds", icon:"nightlife", name:"Tracks",path:"/tracks"},
    {count:2500, about:"World's largest hex quards library", icon:"palette", name:"Palettes",path:"/palettes"},
    {count:1500, about:"Asia's css backgrounds library", icon:"gradient", name:"Gradients",path:"/gradients"},
    {count:22, about:"All possible css patterns collections", icon:"pattern", name:"Patterns",path:"/patterns"},
    {count:268, about:"Time tested stable hex codes", icon:"format_color_fill", name:"Shades",path:"/shades"},
  ]


  nations = [
    {coin: "CAD",cc: "+1",iso: "CA",name: "Canada" },
    {coin: "USD",cc: "+1",iso: "US",name: "United States" },
    {coin: "ZAR",cc: "+27",iso: "ZA",name: "South Africa" },
    {coin: "EUR",cc: "+30",iso: "GR",name: "Greece" },
    {coin: "EUR",cc: "+31",iso: "NL",name: "the Netherlands" },
    {coin: "EUR",cc: "+32",iso: "BE",name: "Belgium" },
    {coin: "EUR",cc: "+33",iso: "FR",name: "France" },
    {coin: "EUR",cc: "+34",iso: "ES",name: "Spain" },
    {coin: "HUF",cc: "+36",iso: "HU",name: "Hungary" },
    {coin: "EUR",cc: "+39",iso: "IT",name: "Italy" },
    {coin: "RON",cc: "+40",iso: "RO",name: "Romania" },
    {coin: "CHF",cc: "+41",iso: "CH",name: "Switzerland" },
    {coin: "EUR",cc: "+43",iso: "AT",name: "Austria" },
    {coin: "GBP",cc: "+44",iso: "UK",name: "United Kingdom" },
    {coin: "DKK",cc: "+45",iso: "DK",name: "Denmark" },
    {coin: "SEK",cc: "+46",iso: "SE",name: "Sweden" },
    {coin: "NOK",cc: "+47",iso: "NO",name: "Norway" },
    {coin: "PLN",cc: "+48",iso: "PL",name: "Poland" },
    {coin: "EUR",cc: "+49",iso: "DE",name: "Germany" },
    {coin: "BRL",cc: "+55",iso: "BR",name: "Brazil" },
    {coin: "SGD",cc: "+65",iso: "SG",name: "Singapore" },
    {coin: "JPY",cc: "+81",iso: "JP",name: "Japan" },
    {coin: "KRW",cc: "+82",iso: "KR",name: "South Korea" },
    {coin: "RUB",cc: "+86",iso: "RU",name: "Russia" },
    {coin: "CNY",cc: "+86",iso: "CH",name: "Mainland China" },
    {coin: "INR",cc: "+91",iso: "IN",name: "India" },
    {coin: "GIP",cc: "+350",iso: "GI",name: "Gibraltar" },
    {coin: "EUR",cc: "+351",iso: "PT",name: "Portugal" },
    {coin: "EUR",cc: "+352",iso: "LU",name: "Luxembourg" },
    {coin: "EUR",cc: "+353",iso: "IE",name: "Ireland" },
    {coin: "ISK",cc: "+354",iso: "IS",name: "Iceland" },
    {coin: "ALL",cc: "+355",iso: "AL",name: "Albania" },
    {coin: "EUR",cc: "+356",iso: "MT",name: "Malta" },
    {coin: "EUR",cc: "+357",iso: "CY",name: "Cyprus" },
    {coin: "EUR",cc: "+358",iso: "FI",name: "Finland" },
    {coin: "BGN",cc: "+359",iso: "BG",name: "Bulgaria" },
    {coin: "EUR",cc: "+370",iso: "LT",name: "Lithuania" },
    {coin: "EUR",cc: "+371",iso: "LV",name: "Latvia" },
    {coin: "EUR",cc: "+372",iso: "EE",name: "Estonia" },
    {coin: "MDL",cc: "+373",iso: "MD",name: "Moldova" },
    {coin: "AMD",cc: "+374",iso: "AM",name: "Armenia" },
    {coin: "BYN",cc: "+375",iso: "BY",name: "Belarus" },
    {coin: "AND",cc: "+376",iso: "AD",name: "Andorra" },
    {coin: "EUR",cc: "+377",iso: "MC",name: "Monaco" },
    {coin: "EUR",cc: "+378",iso: "SM",name: "San Marino" },
    {coin: "EUR",cc: "+379",iso: "VA",name: "Vatican" },
    {coin: "UAH",cc: "+380",iso: "UA",name: "Ukraine" },
    {coin: "RSD",cc: "+381",iso: "RS",name: "Serbia" },
    {coin: "EUR",cc: "+382",iso: "ME",name: "Montenegro" },
    {coin: "HRK",cc: "+385",iso: "HR\t",name: "Croatia" },
    {coin: "EUR",cc: "+386",iso: "SL",name: "Slovenia" },
    {coin: "BAM",cc: "+387",iso: "BA",name: "Bosnia & Herzegovina" },
    {coin: "MKD",cc: "+389",iso: "MK",name: "North Macedonia" },
    {coin: "CZK",cc: "+420",iso: "CZ",name: "Czech Republic" },
    {coin: "EUR",cc: "+421",iso: "SK",name: "Slovakia" },
    {coin: "CHF",cc: "+423",iso: "LI",name: "Liechtenstein"}
];


    

    palatteList = [ 
      "Pastel",
      "Neon",
      "Gold",
      "Vintage",
      "Retro",
      "Light",
      "Dark",
      "Warm",
      "Cold",
      "Summer",
      "Fall",
      "Winter",
      "Spring",
      "Rainbow",
      "Night",
      "Space",
      "Earth",
      "Nature",
      "Sunset",
      "Skin",
      "Food",
      "Cream",
      "Coffee",
      "Christmas",
      "Halloween",
      "Wedding",
      "Kids",
      "Happy",
    ]

    gradientList = [
      {name:"Linear Gradients", info:"linear", code:1},
      {name:"Radial Gradients", info:"radial", code:2},
      {name:"Conic Gradients", info:"conic", code:3},
    ]
    
    patternType = [
      {name:"XXX", color: "#f44336", code:1},
      {name:"XXX", color: "#e91e63", code:2},
      {name:"XXX", color: "#9c27b0", code:3},
      {name:"XXX", color: "#673ab7", code:4},
      {name:"Indigo", color: "#3f51b5", code:5},
      {name:"XXX", color: "#2196f3", code:6},
      {name:"XXX", color: "#03a9f4", code:7},
      {name:"XXX", color: "#00bcd4", code:8},
      {name:"XXX", color: "#009688", code:9},
      {name:"XXX", color: "#4caf50", code:10},
      {name:"XXX", color: "#8bc34a", code:11},
      {name:"XXX", color: "#cddc39", code:12},
      {name:"XXX", color: "#ffeb3b", code:13},
      {name:"XXX", color: "#ffc107", code:14},
      {name:"XXX", color: "#ff9800", code:15},
      {name:"XXX", color: "#ff5722", code:16},
      {name:"XXX", color: "#795548", code:17},
      {name:"XXX", color: "#9e9e9e", code:18},
      {name:"XXX", color: "#607d8b", code:19},
      {name:"XXX", color: "#ffffff", code:20},
      {name:"XXX", color: "#000000", code:21},
    ]

    mapList = [
    {name:"Mercator", info:"Mercator", code:1},
    {name:"Mercator Pacific", info:"MercatorPacific", code:2},
    {name:"Peirce Quincuncial", info:"PeirceQuincuncial", code:3},

    {name:"Continent", info:"Continent", code:4},
    {name:"Region", info:"Region", code:5},
    {name:"Nation", info:"Nation", code:6},
    {name:"State", info:"State", code:7},
    {name:"City", info:"City", code:8},

    {name:"History", info:"History", code:9},
    {name:"Geography", info:"Geography", code:10},
  ]

  tableType = [
    {name:"Chinese", info:"ZH", code:4},
    {name:"English", info:"EN", code:2},
    {name:"French", info:"FR", code:3},
    {name:"Hindi", info:"HI", code:5},
    {name:"Marathi", info:"MA", code:1},
    {name:"Spanish", info:"ES", code:6},
  ]
  fontType = [
    {name:"Arabic", code:1, demo:"يجب أن يُمنح كل إنسان كرامته في كل جزء من العالم."},
    {name:"Amharic", code:29, demo:"ሰው ሁሉ በሁሉም የዓለም ክፍል ክብሩን ሊሰጠው ይገባል ።"},
    {name:"Bengali", code:2, demo:"পৃথিবীর প্রতিটি প্রান্তে প্রতিটি মানুষকে তার মর্যাদা দিতে হবে।"},
    {name:"Chinese (Hong Kong)", code:3, demo:"喺世界嘅每個地方，個個都必須得到尊嚴。"},
    {name:"Chinese (Simplified)", code:4, demo:"在世界的每一个角落，每个人都必须被赋予尊严。"},
    {name:"Chinese (Traditional)", code:5, demo:"在世界的每一個角落，每個人都必須被賦予尊嚴。"},
    {name:"Cyrillic", code:6, demo:"Каждому человеку должно быть предоставлено его достоинство в любой части мира."},
    {name:"Cyrillic Extended", code:7, demo:"Каждому человеку должно быть предоставлено его достоинство в любой части мира."},
    {name:"Devanagari", code:8, demo:"प्रत्येक माणसाला जगाच्या प्रत्येक भागात त्याची प्रतिष्ठा दिली पाहिजे."},
    {name:"Greek", code:9, demo:"Σε κάθε άνθρωπο πρέπει να δοθεί η αξιοπρέπειά του σε κάθε μέρος του κόσμου."},
    {name:"Greek Extended", code:10, demo:"Σε κάθε άνθρωπο πρέπει να δοθεί η αξιοπρέπειά του σε κάθε μέρος του κόσμου."},
    {name:"Gujarati", code:11, demo:"વિશ્વના દરેક ભાગમાં દરેક માણસને તેનું ગૌરવ મળવું જોઈએ."},
    {name:"Gurmukhi", code:12, demo:"ਹਰ ਮਨੁੱਖ ਨੂੰ ਦੁਨੀਆ ਦੇ ਹਰ ਹਿੱਸੇ ਵਿੱਚ ਉਸਦੀ ਇੱਜ਼ਤ ਦਿੱਤੀ ਜਾਣੀ ਚਾਹੀਦੀ ਹੈ।"},
    {name:"Hebrew", code:13, demo:"יש לתת לכל אדם את כבודו בכל חלקי העולם."},
    {name:"Japanese", code:14, demo:"すべての人は、世界のあらゆる場所で尊厳を与えられなければなりません。"},
    {name:"Kannada", code:15, demo:"ಪ್ರಪಂಚದ ಪ್ರತಿಯೊಂದು ಭಾಗದಲ್ಲೂ ಪ್ರತಿಯೊಬ್ಬ ಮನುಷ್ಯನಿಗೂ ಅವನ ಘನತೆಯನ್ನು ನೀಡಬೇಕು."},
    {name:"Khmer", code:16, demo:"មនុស្សគ្រប់រូបត្រូវតែផ្តល់ភាពថ្លៃថ្នូររបស់ខ្លួននៅគ្រប់ផ្នែកនៃពិភពលោក។"},
    {name:"Korean", code:17, demo:"모든 사람은 세계 어느 곳에서나 자신의 존엄성을 부여받아야 합니다."},
    {name:"Latin", code:18, demo:"Unicuique homini tribuendum est suam dignitatem in quavis parte terrarum."},
    {name:"Latin Extended", code:19, demo:"Every man must be given his dignity in every part of world."},
    {name:"Malayalam", code:20, demo:"ലോകത്തിന്റെ എല്ലാ ഭാഗത്തും ഓരോ മനുഷ്യനും അവന്റെ മഹത്വം നൽകണം."},
    {name:"Myanmar", code:21, demo:"လူတိုင်းကို ကမ္ဘာ့ဒေသတိုင်းမှာ ဂုဏ်သိက္ခာရှိရမယ်။"},
    {name:"Oriya", code:22, demo:"ପ୍ରତ୍ୟେକ ବ୍ୟକ୍ତିଙ୍କୁ ଦୁନିଆର ପ୍ରତ୍ୟେକ ଭାଗରେ ନିଜର ସମ୍ମାନ ଦିଆଯିବା ଆବଶ୍ୟକ |"},
    {name:"Sinhala", code:23, demo:"ලෝකයේ සෑම තැනකම සෑම මිනිසෙකුටම ඔහුගේ ගෞරවය ලබා දිය යුතුය."},
    {name:"Tamil", code:24, demo:"உலகின் ஒவ்வொரு பகுதியிலும் ஒவ்வொரு மனிதனுக்கும் அவனது கௌரவம் வழங்கப்பட வேண்டும்."},
    {name:"Telugu", code:25, demo:"ప్రపంచంలోని ప్రతి ప్రాంతంలో ప్రతి మనిషికి తన గౌరవం ఇవ్వాలి."},
    {name:"Thai", code:26, demo:"ทุกคนต้องได้รับศักดิ์ศรีของตนในทุกส่วนของโลก"},
    {name:"Tibetan", code:27, demo:"མི་རེ་རེ་ཚང་མར་ངེས་པར་དུ་འཛམ་གླིང་གི་ས་ཆ་རེ་རེར་རང་ཉིད་ཀྱི་ལ་རྒྱ་ཡོད་དགོས།"},
    {name:"Vietnamese", code:28, demo:"Mỗi người đàn ông phải được ban cho phẩm giá của mình ở mọi nơi trên thế giới."},
    {name:"Other", code:99, demo:"0 1 2 3 4 5 6 7 8 9"},
  ]
  iconCat = [
    "Accessibility",
    "Adhesive Bandage",
    "Airport",
    "Football",
    "Anchor",
    "Antenna",
    "Archive",
    "Arrow",
    "Audio", 
    "Award",
    "Badge",
    "Badminton",
    "Banknote",
    "Barcode",
    "Baseball",
    "Basket",
    "Basketball",
    "Battery",
    "Bed",
    "Beer",
    "Bell",
    "Bicycle",
    "Binoculars",
    "Bitcoin",
    "Book",
    "Bookmark",
    "Bowling",
    "Boxing",
    "Brick",
    "Bus",
    "Brightness",
    "Briefcase",
    "Building",
    "Bug",
    "Cargo",
    "Calculator",
    "Car",
    "Candy",
    "Calendar",
    "Coffee",
    "Checkout",
    "Chrome",
    "Circle",
    "Clipboard",
    "Code",
    "Cloud",
    "Code Fork",
    "Christmas",
    "Clothing",
    "Coin",
    "Compass",
    "Computer",
    "Connection",
    "Construction",
    "Control Panel",
    "Flashlight",

    "Direction",
    "Disc",
    "Disk",
    "Door",
    "Download",
    "Cricket",
    "Fish",

    "Eraser",
    "Eye",
    "Edit",
    "Error",
    "Equalizer",
    "Email",
    "Easter",
    "Eat",
    "Drop",
    "Cook",
    "CPU",
    "Copy",
    "Copyright",
    "Crop",
    "Crosshair",
    "CV",
    "Crown",
    "Cube",
    "Cut",
    "Cursor",
    "Customer",
    "Diamond",
    "Database",
    "Dashboard",
    "Danger",
    "Delivery",
    "Eyedropper",
    "Favorite",
    "Firewall",
    "Filter",
    "Flag",

    "Medal",
    "Golf",
    "Hexagon",
    "Hearing",
    "Glasses",
    "Flower",
    "Headphones",
    "Fax",
    "File",
    "Fingerprint",
    "Home",
    "Help",
    "Handshake",
    "Gear",
    "Friend",
    "Flask",
    "Gavel",
    "Loading",
    "Magic",
    "Lock",
    "Folder",
    "Forbidden",
    "Keyboard",
    "Key",
    "Fullscreen",
    "Gamepad",
    "Idea",
    "Gender",
    "Infinity",
    "Inbox",
    "ID Card",
    "Info",
    "Globe",
    "Generation",
    "Language",
    "Marketing",
    "Laptop",
    "Layer",
    "Map",
    "Lifebuoy",
    "Light Bulb",
    "Log Out",
    "Magnifier",
    "Link",
    "Magnet",
    "Location",
    
    "Chart",
    "Sports",
    "Card",
    "Currency",
    "Food",
    "Brand",
  ];
  
  colorz = [
    {id:"red", name:"Red", p:[
      {n:"50", c:"#FFEBEE"},
      {n:"100", c:"#FFCDD2"},
      {n:"200", c:"#EF9A9A"},
      {n:"300", c:"#E57373"},
      {n:"400", c:"#EF5350"},
      {n:"500", c:"#F44336"},
      {n:"600", c:"#E53935"},
      {n:"700", c:"#D32F2F"},
      {n:"800", c:"#C62828"},
      {n:"900", c:"#B71C1C"},
      {n:"A100", c:"#FF8A80"},
      {n:"A200", c:"#FF5252"},
      {n:"A400", c:"#FF1744"},
      {n:"A700", c:"#D50000"},
    ]},
    {id:"pink", name:"Pink", p:[
      {n:"50", c:"#FCE4EC"},
      {n:"100", c:"#F8BBD0"},
      {n:"200", c:"#F48FB1"},
      {n:"300", c:"#F06292"},
      {n:"400", c:"#EC407A"},
      {n:"500", c:"#E91E63"},
      {n:"600", c:"#D81B60"},
      {n:"700", c:"#C2185B"},
      {n:"800", c:"#AD1457"},
      {n:"900", c:"#880E4F"},
      {n:"A100", c:"#FF80AB"},
      {n:"A200", c:"#FF4081"},
      {n:"A400", c:"#F50057"},
      {n:"A700", c:"#C51162"},
    ]},
    {id:"purple", name:"Purple", p:[
      {n:"50", c:"#F3E5F5"},
      {n:"100", c:"#E1BEE7"},
      {n:"200", c:"#CE93D8"},
      {n:"300", c:"#BA68C8"},
      {n:"400", c:"#AB47BC"},
      {n:"500", c:"#9C27B0"},
      {n:"600", c:"#8E24AA"},
      {n:"700", c:"#7B1FA2"},
      {n:"800", c:"#6A1B9A"},
      {n:"900", c:"#4A148C"},
      {n:"A100", c:"#EA80FC"},
      {n:"A200", c:"#E040FB"},
      {n:"A400", c:"#D500F9"},
      {n:"A700", c:"#AA00FF"},
    ]},
    {id:"deep_purple", name:"Deep Purple", p:[
      {n:"50", c:"#EDE7F6"},
      {n:"100", c:"#D1C4E9"},
      {n:"200", c:"#B39DDB"},
      {n:"300", c:"#9575CD"},
      {n:"400", c:"#7E57C2"},
      {n:"500", c:"#673AB7"},
      {n:"600", c:"#5E35B1"},
      {n:"700", c:"#512DA8"},
      {n:"800", c:"#4527A0"},
      {n:"900", c:"#311B92"},
      {n:"A100", c:"#B388FF"},
      {n:"A200", c:"#7C4DFF"},
      {n:"A400", c:"#651FFF"},
      {n:"A700", c:"#6200EA"},
    ]},
    {id:"indigo", name:"Indigo", p:[
      {n:"50", c:"#E8EAF6"},
      {n:"100", c:"#C5CAE9"},
      {n:"200", c:"#9FA8DA"},
      {n:"300", c:"#7986CB"},
      {n:"400", c:"#5C6BC0"},
      {n:"500", c:"#3F51B5"},
      {n:"600", c:"#3949AB"},
      {n:"700", c:"#303F9F"},
      {n:"800", c:"#283593"},
      {n:"900", c:"#1A237E"},
      {n:"A100", c:"#8C9EFF"},
      {n:"A200", c:"#536DFE"},
      {n:"A400", c:"#3D5AFE"},
      {n:"A700", c:"#304FFE"},
    ]},
    {id:"blue", name:"Blue", p:[
      {n:"50", c:"#E3F2FD"},
      {n:"100", c:"#BBDEFB"},
      {n:"200", c:"#90CAF9"},
      {n:"300", c:"#64B5F6"},
      {n:"400", c:"#42A5F5"},
      {n:"500", c:"#2196F3"},
      {n:"600", c:"#1E88E5"},
      {n:"700", c:"#1976D2"},
      {n:"800", c:"#1565C0"},
      {n:"900", c:"#0D47A1"},
      {n:"A100", c:"#82B1FF"},
      {n:"A200", c:"#448AFF"},
      {n:"A400", c:"#2979FF"},
      {n:"A700", c:"#2962FF"},
    ]},
    {id:"light_blue", name:"Light Blue", p:[
      {n:"50", c:"#E1F5FE"},
      {n:"100", c:"#B3E5FC"},
      {n:"200", c:"#81D4FA"},
      {n:"300", c:"#4FC3F7"},
      {n:"400", c:"#29B6F6"},
      {n:"500", c:"#03A9F4"},
      {n:"600", c:"#039BE5"},
      {n:"700", c:"#0288D1"},
      {n:"800", c:"#0277BD"},
      {n:"900", c:"#01579B"},
      {n:"A100", c:"#80D8FF"},
      {n:"A200", c:"#40C4FF"},
      {n:"A400", c:"#00B0FF"},
      {n:"A700", c:"#0091EA"},
    ]},
    {id:"cyan", name:"Cyan", p:[
      {n:"50", c:"#E0F7FA"},
      {n:"100", c:"#B2EBF2"},
      {n:"200", c:"#80DEEA"},
      {n:"300", c:"#4DD0E1"},
      {n:"400", c:"#26C6DA"},
      {n:"500", c:"#00BCD4"},
      {n:"600", c:"#00ACC1"},
      {n:"700", c:"#0097A7"},
      {n:"800", c:"#00838F"},
      {n:"900", c:"#006064"},
      {n:"A100", c:"#84FFFF"},
      {n:"A200", c:"#18FFFF"},
      {n:"A400", c:"#00E5FF"},
      {n:"A700", c:"#00B8D4"},
    ]},
    {id:"teal", name:"Teal", p:[
      {n:"50", c:"#E0F2F1"},
      {n:"100", c:"#B2DFDB"},
      {n:"200", c:"#80CBC4"},
      {n:"300", c:"#4DB6AC"},
      {n:"400", c:"#26A69A"},
      {n:"500", c:"#009688"},
      {n:"600", c:"#00897B"},
      {n:"700", c:"#00796B"},
      {n:"800", c:"#00695C"},
      {n:"900", c:"#004D40"},
      {n:"A100", c:"#A7FFEB"},
      {n:"A200", c:"#64FFDA"},
      {n:"A400", c:"#1DE9B6"},
      {n:"A700", c:"#00BFA5"},
    ]},
    {id:"green", name:"Green", p:[
      {n:"50", c:"#E8F5E9"},
      {n:"100", c:"#C8E6C9"},
      {n:"200", c:"#A5D6A7"},
      {n:"300", c:"#81C784"},
      {n:"400", c:"#66BB6A"},
      {n:"500", c:"#4CAF50"},
      {n:"600", c:"#43A047"},
      {n:"700", c:"#388E3C"},
      {n:"800", c:"#2E7D32"},
      {n:"900", c:"#1B5E20"},
      {n:"A100", c:"#B9F6CA"},
      {n:"A200", c:"#69F0AE"},
      {n:"A400", c:"#00E676"},
      {n:"A700", c:"#00C853"},
    ]},
    {id:"light_green", name:"Light Green", p:[
      {n:"50", c:"#F1F8E9"},
      {n:"100", c:"#DCEDC8"},
      {n:"200", c:"#C5E1A5"},
      {n:"300", c:"#AED581"},
      {n:"400", c:"#9CCC65"},
      {n:"500", c:"#8BC34A"},
      {n:"600", c:"#7CB342"},
      {n:"700", c:"#689F38"},
      {n:"800", c:"#558B2F"},
      {n:"900", c:"#33691E"},
      {n:"A100", c:"#CCFF90"},
      {n:"A200", c:"#B2FF59"},
      {n:"A400", c:"#76FF03"},
      {n:"A700", c:"#64DD17"},
    ]},
    {id:"lime", name:"Lime", p:[
      {n:"50", c:"#F9FBE7"},
      {n:"100", c:"#F0F4C3"},
      {n:"200", c:"#E6EE9C"},
      {n:"300", c:"#DCE775"},
      {n:"400", c:"#D4E157"},
      {n:"500", c:"#CDDC39"},
      {n:"600", c:"#C0CA33"},
      {n:"700", c:"#AFB42B"},
      {n:"800", c:"#9E9D24"},
      {n:"900", c:"#827717"},
      {n:"A100", c:"#F4FF81"},
      {n:"A200", c:"#EEFF41"},
      {n:"A400", c:"#C6FF00"},
      {n:"A700", c:"#AEEA00"},
    ]},
    {id:"yellow", name:"Yellow", p:[
      {n:"50", c:"#FFFDE7"},
      {n:"100", c:"#FFF9C4"},
      {n:"200", c:"#FFF59D"},
      {n:"300", c:"#FFF176"},
      {n:"400", c:"#FFEE58"},
      {n:"500", c:"#FFEB3B"},
      {n:"600", c:"#FDD835"},
      {n:"700", c:"#FBC02D"},
      {n:"800", c:"#F9A825"},
      {n:"900", c:"#F57F17"},
      {n:"A100", c:"#FFFF8D"},
      {n:"A200", c:"#FFFF00"},
      {n:"A400", c:"#FFEA00"},
      {n:"A700", c:"#FFD600"},
    ]},
    {id:"amber", name:"Amber", p:[
      {n:"50", c:"#FFF8E1"},
      {n:"100", c:"#FFECB3"},
      {n:"200", c:"#FFE082"},
      {n:"300", c:"#FFD54F"},
      {n:"400", c:"#FFCA28"},
      {n:"500", c:"#FFC107"},
      {n:"600", c:"#FFB300"},
      {n:"700", c:"#FFA000"},
      {n:"800", c:"#FF8F00"},
      {n:"900", c:"#FF6F00"},
      {n:"A100", c:"#FFE57F"},
      {n:"A200", c:"#FFD740"},
      {n:"A400", c:"#FFC400"},
      {n:"A700", c:"#FFAB00"},
    ]},
    {id:"orange", name:"Orange", p:[
      {n:"50", c:"#FFF3E0"},
      {n:"100", c:"#FFE0B2"},
      {n:"200", c:"#FFCC80"},
      {n:"300", c:"#FFB74D"},
      {n:"400", c:"#FFA726"},
      {n:"500", c:"#FF9800"},
      {n:"600", c:"#FB8C00"},
      {n:"700", c:"#F57C00"},
      {n:"800", c:"#EF6C00"},
      {n:"900", c:"#E65100"},
      {n:"A100", c:"#FFD180"},
      {n:"A200", c:"#FFAB40"},
      {n:"A400", c:"#FF9100"},
      {n:"A700", c:"#FF6D00"},
    ]},
    {id:"deep_orange", name:"Deep Orange", p:[
      {n:"50", c:"#FBE9E7"},
      {n:"100", c:"#FFCCBC"},
      {n:"200", c:"#FFAB91"},
      {n:"300", c:"#FF8A65"},
      {n:"400", c:"#FF7043"},
      {n:"500", c:"#FF5722"},
      {n:"600", c:"#F4511E"},
      {n:"700", c:"#E64A19"},
      {n:"800", c:"#D84315"},
      {n:"900", c:"#BF360C"},
      {n:"A100", c:"#FF9E80"},
      {n:"A200", c:"#FF6E40"},
      {n:"A400", c:"#FF3D00"},
      {n:"A700", c:"#DD2C00"},
    ]},
    {id:"brown", name:"Brown", p:[
      {n:"50", c:"#EFEBE9"},
      {n:"100", c:"#D7CCC8"},
      {n:"200", c:"#BCAAA4"},
      {n:"300", c:"#A1887F"},
      {n:"400", c:"#8D6E63"},
      {n:"500", c:"#795548"},
      {n:"600", c:"#6D4C41"},
      {n:"700", c:"#5D4037"},
      {n:"800", c:"#4E342E"},
      {n:"900", c:"#3E2723"},
    ]},
    {id:"grey", name:"Gray", p:[
      {n:"50", c:"#FAFAFA"},
      {n:"100", c:"#F5F5F5"},
      {n:"200", c:"#EEEEEE"},
      {n:"300", c:"#E0E0E0"},
      {n:"400", c:"#BDBDBD"},
      {n:"500", c:"#9E9E9E"},
      {n:"600", c:"#757575"},
      {n:"700", c:"#616161"},
      {n:"800", c:"#424242"},
      {n:"900", c:"#212121"},
    ]},
    {id:"blue_grey", name:"Blue Gray", p:[
      {n:"50", c:"#ECEFF1"},
      {n:"100", c:"#CFD8DC"},
      {n:"200", c:"#B0BEC5"},
      {n:"300", c:"#90A4AE"},
      {n:"400", c:"#78909C"},
      {n:"500", c:"#607D8B"},
      {n:"600", c:"#546E7A"},
      {n:"700", c:"#455A64"},
      {n:"800", c:"#37474F"},
      {n:"900", c:"#263238"},
    ]},
    {id:"black_and_white", name:"Black & White", p:[
      {n:"Black", c:"#000000"},
      {n:"White", c:"#FFFFFF"},
    ]},
  ]



  globalMaps = [
    { title:"Mercator - World map" , id:"KCchYPIYgNMqfARGXgGB", area:["world"] },
    { title:"Mercator - World map detailed" , id:"2UXXeYYQz6Vg9PLrQNdi", area:["world"] },
    { title:"Mercator Pacific - World map" , id:"JMIFHJ14U0Mtr93JTfOK", area:["world"] },
    { title:"Globe Pacific - World map" , id:"wZZYVnjusfPpcAneEfzL" },
    { title:"Africa", id:"lAGGD1HIzbcpS1aB5K8L", area:["africa"] },
    { title:"Africa Detailed", id:"z5z8j4nDFJpAGNjTlOQF", area:["africa"] },
    { title:"Caribbean", id:"DzxsjXB0W03vxIZU9Ix1", area:["americas"] },
    { title:"Europe", id:"yJY5PAJIpLee3uAjs2YQ", area:["europe"] },
    { title:"Europe Detailed", id:"VIeZyRTZ9DXk2U0soxey", area:["europe"] },
    { title:"Indo China", id:"5HdiIHDm81mdN6inP9FP" },
    { title:"Asia Detailed", id:"5GEF7zp4qWAc9Bail9RY", area:["world", "eastAsia", "southAsia", "westAsia"] },
    { title:"Middle East", id:"retQIf6wx0QTWAq1SCJd" },
    { title:"North America", id:"ZKouFGUIXjl0JHJubzPH", area:["americas"] },
    { title:"South America", id:"ZCh3pFBe2iOLg7or7LJU", area:["americas"] },
    { title:"Americas Detailed", id:"Ddr1qwe7CYkdshiMmt9x", area:["americas"] },
  ]
  nationMaps = [
    {title:"Afghanistan", id:"EXrnidf7ArDEriwrAA4q", area:["southAsia"] },
    {title:"Albania", id:"GbBkUYWNlePlshiIfnvI" },
    {title:"Algeria", id:"iANOO8TyYgN45lKlBakR", area:["africa"] },
    {title:"Andorra", id:"cPL5FdUGR2iiT1aFZ5FJ" },
    {title:"Angola", id:"427HfmifP5fbecYUnioQ", area:["africa"] },
    {title:"Anguilla", id:"3SDfyi4qGeIKmGuPJ35o" },
    {title:"Antigua and Barbuda", id:"eJL7Qd90zx8gagXo6yKt" },
    {title:"Argentina", id:"apQehJk9xzZuYbwAdQUH" },
    {title:"Armenia", id:"boGn3aYCN8HEO8Y32j1P" },
    {title:"Aruba", id:"RZ4B3O23Yh7AY4jAT934" },
    {title:"Australia", id:"SZSmJx7MnYzXyuRc10YY" },
    {title:"Austria", id:"T0cbToHiJblkEK07DsRF", area:["europe"] },
    {title:"Azerbaijan", id:"JvGCRv69E4EKohnOPoPx" },
    {title:"Bahamas", id:"9I33F19ai1xtBqUlxFWw" },
    {title:"Bahrain", id:"bxRQFZH6y5IdShjPT6Gh" },
    {title:"Bangladesh", id:"fMn1LuurkaBjLvrDcqt0", area:["southAsia"] },
    {title:"Barbados", id:"TvMI2IrcirWv3ZjiMSIv" },
    {title:"Belarus", id:"bYNieLBHNOgtdqJbycxC" },
    {title:"Belgium", id:"nyxbTozYJ6MaKNi2MYhI" },
    {title:"Belize", id:"chZAR5pHiNAudLG8vR1d" },
    {title:"Benin", id:"6S3uAcUWELSIQ6WLUHRl" },
    {title:"Bermuda", id:"jwZfYPfeOln2Q1KbNMy6" },
    {title:"Bhutan", id:"xnXFskwHLugaoGjjvU3f", area:["southAsia"] },
    {title:"Bolivia", id:"yWGYxbg0EXnf5ds9cqEo", area:["americas"] },
    {title:"Bosnia and Herzegovina", id:"hJwt8BegrqA46GzMpx4E" },
    {title:"Botswana", id:"wfOF80BEGQkQ7i7Mj49Q" },
    {title:"Brazil", id:"ZPLW0w0Nb3qeuv9gttUc", area:["americas"] },
    {title:"British Virgin Islands", id:"DoOSbPZk0q7jR5DytsMp" },
    {title:"Brunei", id:"rUX54YjRgMMDnLirmyYq" },
    {title:"Bulgaria", id:"4FeGDYlSmg83qH1EZqGB" },
    {title:"Burkina Faso", id:"MjW4T8fDz7SUeWF6vATQ" },
    {title:"Burundi", id:"Cm01x1WXM4nZLxElN1zF" },
    {title:"Cambodia", id:"zNvlt6saCdYtPtUz1wAW" },
    {title:"Cameroon", id:"9CVhYLizGKo2xXpcObfs" },
    {title:"Canada", id:"mtj0hkPGO3XnXh31S0ZD" },
    {title:"Cape Verde", id:"xn7lx7Szi8WPZaAo72eO" },
    {title:"Cayman Islands", id:"sw3GqUBwlq2wPDDKPmdi" },
    {title:"Central African Republic", id:"Us6ZefoDchFLGiXBzvOO", area:["africa"] },
    {title:"Chad", id:"BNMiCxBHuScV0kuekb88" },
    {title:"Chile", id:"ix4WilzeqmYUWNxfamBN", area:["americas"] },
    {title:"China", id:"at9tXmYElAsy301lhGM7", area:["eastAsia"] },
    {title:"Colombia", id:"o1fXEsS56Ksv7YHD3WOt", area:["americas"] },
    {title:"Comoros", id:"nRkke9gOoWkPFBcstVCr" },
    {title:"Costa Rica", id:"KQc2sTNviLXE2FNwMkZC" },
    {title:"Croatia", id:"gnSpIenLG7gBFohKT1qv" },
    {title:"Cuba", id:"KZdtYzd7QkU0BT9tltt0", area:["americas"] },
    {title:"Curaco (Netherlands)", id:"0FYUlo0cv9EKQWmagPB6" },
    {title:"Cyprus", id:"53LV7VbLD7JfJPOIDSVd" },
    {title:"Czech Republic", id:"J9INLJvvWgKoZxlrlKQK" },
    {title:"Côte d'Ivoire", id:"5maM0goo6oIldntffUw6" },
    {title:"Democratic Republic of the Congo", id:"2NF7Y3Qal25ZFNYu4qZL", area:["africa"] },
    {title:"Denmark", id:"t6mPX2xen0ZGyTD4JRx8", area:["europe"] },
    {title:"Djibouti", id:"Azy00VSpylD4nJTWWC88" },
    {title:"Dominica", id:"WNQBjrHdo1QX3Ajvx8ne" },
    {title:"Dominican Republic", id:"vcfjbJ9XicvSanl8NPg7" },
    {title:"Ecuador", id:"IeUtKbkWJkiD8Jg6Y2CL", area:["americas"] },
    {title:"Egypt", id:"cGfgC4alveUppz1MiH24", area:["africa"] },
    {title:"El Salvador", id:"THCprvFcz9yuV44NgzAd" },
    {title:"Equatorial Guinea", id:"LC8DHvoS46cvnsrNZQ0C" },
    {title:"Eritrea", id:"KqMMLwMqYfwg6P6nBIfm" },
    {title:"Estonia", id:"30OmtTFP79GzWH5HfGKB" },
    {title:"Ethiopia", id:"uvcJzj5c4LpsiJ67BGiM", area:["africa"] },
    {title:"Faeroe Islands", id:"NqHfaUfvcWd2oH1mvhco" },
    {title:"Falkland Islands", id:"sQyaKZWO8m16lOPqjIH7" },
    {title:"Fiji", id:"u1t28pjL01IrKMatVizx" },
    {title:"Finland", id:"jGR7CL0EXbdXh5y02dWK" },
    {title:"France", id:"ipnA5sm3bImNkSf3wGHa", area:["europe"] },
    {title:"French Polynesia", id:"cP54TDIU97l4jyY09miy" },
    {title:"Gabon", id:"Jd8GtZVNUTgIBXBiw3tA" },
    {title:"Georgia", id:"w21jd0QUcKDATgnPD528" },
    {title:"Germany", id:"WKXXRFo7BSlSfFnNwpjY", area:["europe"] },
    {title:"Ghana", id:"rKYx9l5nYAwLXEm5Mfge" },
    {title:"Greece", id:"0KIjQuGOx50T52ZRnERd", area:["europe"] },
    {title:"Greenland", id:"jswHoE1cgJWQWwFYJaEe" },
    {title:"Grenada", id:"8aVqI9s5It1I9pPGY5XK" },
    {title:"Guatemala", id:"nhJthyrfVmtZn4q7Jmq7" },
    {title:"Guinea", id:"mS8eGB4OHEfOhV52Qvf5" },
    {title:"Guinea-Bissau", id:"dgzmicYGL83Nq5IkEi62" },
    {title:"Guyana", id:"41UKlwwurGUGTYA1GzoT" },
    {title:"Haiti", id:"VvWKwwSraZaxikkesCyS", area:["americas"] },
    {title:"Honduras", id:"7DqBJRe5ywRH5sgu7bt3" },
    {title:"Hong Kong", id:"VATAalogj7LVHKJr3XCH" },
    {title:"Hungary", id:"P03dQFpKHRLxp4848ylA" },
    {title:"Iceland", id:"fyNLjCoQJFqOijyNSoAn" },
    {title:"India", id:"VW3kjXIGi9oqbaYrjC6G", area:["southAsia"] },
    {title:"Indonesia", id:"CVFU4spYOdOmDdo24xMg", area:["eastAsia"] },
    {title:"Iran", id:"TcWy3aZqprnxEZ0BgNBF", area:["westAsia"] },
    {title:"Iraq", id:"VviWY8G8Pa301GL4tpwP", area:["westAsia"] },
    {title:"Ireland", id:"WlfmGuJ0lJCAOi6vXt3G" },
    {title:"Israel", id:"LxUvcK2nTxYlVVAlK4dl", area:["westAsia"] },
    {title:"Italy", id:"VIX3oszCVxqkH7Smm60A", area:["europe"] },
    {title:"Jamaica", id:"axFXQI3saVvM0NrUvraM" },
    {title:"Japan", id:"xPIRKTgglbQhlkrp0Igw", area:["eastAsia"] },
    {title:"Jordan", id:"A8aAqsdQu3dHOAGlmepr" },
    {title:"Kazakhstan", id:"Vh6YoEiJFO3E07mg8NUT" },
    {title:"Kenya", id:"eKMOJtFDZXn0ZNu4jbT5", area:["africa"] },
    {title:"Kuwait", id:"oEbFh94hDN9f6Jdr9bTV" },
    {title:"Kyrgyzstan", id:"11whIZyznmW4vC5GbC4G" },
    {title:"Laos", id:"bsvpT7bvtYDO5uBZM2Hj" },
    {title:"Latvia", id:"rA6rzjESk9DGJia4RNXx" },
    {title:"Lebanon", id:"mPHMwJv3ttIV14xpq3TX" },
    {title:"Lesotho", id:"iBNYmKPJkmcZjffIcJg3" },
    {title:"Liberia", id:"dJQ7LdJhKw9LSxFA1CdJ" },
    {title:"Libya", id:"gGiuQC91WPNpfSpNAPas" },
    {title:"Liechtenstein", id:"feCrepdPh7LfYbBny165" },
    {title:"Lithuania", id:"7ZM9ivqYaXjW4SO0gKib" },
    {title:"Luxembourg", id:"Gd0LEI97ecKgn1qBJtS3" },
    {title:"Macedonia", id:"vbixZNsrJOlhOZi5ekT5" },
    {title:"Madagascar", id:"Z3DWn5K1g6w3FsI1ZSxR" },
    {title:"Malawi", id:"M0JnpXushuoB1SFFOADe" },
    {title:"Malaysia", id:"OwAjqNHaEH3zkR8PlxDx", area:["eastAsia"] },
    {title:"Maldives", id:"OA8hQwrXoTPC4XUOhhOQ" },
    {title:"Mali", id:"vLhGAyiCDrpygA1YiOUz" },
    {title:"Malta", id:"iMdfzPzXK13FGJXpt9k3" },
    {title:"Mauritania", id:"VR56prK24u0I2LnMpXOR" },
    {title:"Mauritius", id:"OVPaUGmEehP1KCmZ5n8D" },
    {title:"Mexico", id:"cQveyFD0AAEUYR9Nw65P", area:["americas"] },
    {title:"Moldova", id:"Yw2cVC6OIMzc2mXjh7my" },
    {title:"Mongolia", id:"uU9qq6wPkfJgFjSv74fn" },
    {title:"Montenegro", id:"4PajnMfWlJnR6R5A1MXq" },
    {title:"Montserrat", id:"Q3G1Kmyy8piWsU6H7qDw" },
    {title:"Morocco", id:"kyyKgyLypPZhdeLTQwOd", area:["africa"] },
    {title:"Mozambique", id:"HqWV5obhMEpA72gy4w8B" },
    {title:"Myanmar", id:"L0dDn2VsuMrvOckkekSF", area:["eastAsia"] },
    {title:"Namibia", id:"vJO1NilNDSS2WTU48ffW" },
    {title:"Nauru", id:"uDcBihqorIHCdyzy86eT" },
    {title:"Nepal", id:"IwjlFahRE3FuFP8B7bF4", area:["southAsia"] },
    {title:"Netherlands", id:"HACUMk2dbAqsrwyIguSI" },
    {title:"New Caledonia", id:"sPD9MHrnFERleCtwXl3y" },
    {title:"New Zealand", id:"Q00B7Nroq1vQPPQYX4SK" },
    {title:"Nicaragua", id:"q0PMyzNLGdAnkPMxXgYY" },
    {title:"Niger", id:"5BK3dcsK7TPHKFLlvQIh" },
    {title:"Nigeria", id:"1DKbmeIZJ0C5yc0IuYp0", area:["africa"] },
    {title:"North Korea", id:"Z0QyDlPCj9UNrPDTEChR", area:["eastAsia"] },
    {title:"Norway", id:"VbQvePlrdcjluE1Fpddg" },
    {title:"Oman", id:"Z3KQktXL68WH1ZsD9Sm5" },
    {title:"Pakistan", id:"SgglB2nHgn1qSI7ESZ52", area:["southAsia"] },
    {title:"Palestine", id:"fr1yg6lNTZgxAqBAAnFO" },
    {title:"Panama", id:"yrl7qzffRvrxwktkqMLF" },
    {title:"Papua New Guinea", id:"tvn804FYRAtHpiZVlY4m" },
    {title:"Paraguay", id:"KkrV52Q7ey8a2yaJYLsf" },
    {title:"Peru", id:"AniEewofMFy6Eo46wUZW", area:["americas"] },
    {title:"Philippines", id:"s2F9yZDrSYYf3uAAlpcy", area:["eastAsia"] },
    {title:"Pitcairn Islands", id:"rMXYosHHlZJTXhUJdh8y" },
    {title:"Poland", id:"iprLBnFN49lkh153ndSD", area:["europe"] },
    {title:"Portugal", id:"9bmhQyQyBnleP1NxIZ8o", area:["europe"] },
    {title:"Puerto Rico", id:"9kxoDCiPsAk9xY47z6HN" },
    {title:"Qatar", id:"jeLzw1iOPCwNF7EXGWQ9", area:["westAsia"] },
    {title:"Republic of Congo", id:"2oXVheAeKuEFjPDmaPHw" },
    {title:"Romania", id:"hjyJP3llzO6C3zSdqULo" },
    {title:"Russian Federation", id:"fmtMXbLSwGXsHXoLM8dP", area:["europe"] },
    {title:"Rwanda", id:"mzZZ17tu5S9OXh2UjfYd" },
    {title:"Saint Kitts and Nevis", id:"iLRxC3FxCpGVpGJHtECH" },
    {title:"Saint Lucia", id:"dGpFOIrvR4LIUYToSxJ7" },
    {title:"Saint Martin (Dutch)", id:"y0J3JDJK0CQRj8Wx3GXs" },
    {title:"Saint Martin (French)", id:"53XrUJFmRLiArUnvbP9N" },
    {title:"Saint Vincent and the Grenadines", id:"99HP4D3Cqx5tbiGstNhn" },
    {title:"Saudi Arabia", id:"Wr36OItVQEIKWiDjuBmt", area:["westAsia"] },
    {title:"Senegal", id:"YDjM0mA6vPNA5nT3lyWj" },
    {title:"Serbia", id:"Y7d7fUHDLb8xH9kCVtxv", area:["europe"] },
    {title:"Seychelles", id:"BMKZi8U7fqQyWxpVkdio" },
    {title:"Sierra Leone", id:"0QfLy8ljoObhbFUPwIpA" },
    {title:"Singapore", id:"kMv1Qo4xVZ9OgOPqO8Ww", area:["eastAsia"] },
    {title:"Slovakia", id:"18LEJ5zpBOB3wET1ClGp" },
    {title:"Slovenia", id:"fcEJoZDHELxfvJ12mNAU" },
    {title:"Solomon Islands", id:"I9t2xid68dcmriLblg6P" },
    {title:"Somalia", id:"TxCQMZehcDvGZiR3Ba4H" },
    {title:"South Africa", id:"6ZPQcx1iMHfpw5j59kU6", area:["africa"] },
    {title:"South Korea", id:"iQfkUEb9pQWlw4NGwn7y", area:["eastAsia"] },
    {title:"South Sudan", id:"fzJCumkO5VVShiLB2ics" },
    {title:"Spain", id:"QFwlcyDU8cuUDDrTthe9", area:["europe"] },
    {title:"Sri Lanka", id:"EfpOSjKlQATVVLSRQXBm", area:["southAsia"] },
    {title:"Sudan", id:"ZvPfwhb5E9talzffpeiy", area:["africa"] },
    {title:"Suriname", id:"Ize6tFZtQYbKckgQuNaZ" },
    {title:"Swaziland", id:"4HTKS2XIaXOo3g9qFBQ5" },
    {title:"Sweden", id:"oUxVsjU1rzF9XasNczBt", area:["europe"] },
    {title:"Switzerland", id:"bkHO88hM8mxr9unTQaLk", area:["europe"] },
    {title:"Syria", id:"Yqi5Z5CFwvTbH9M8Qf0c", area:["westAsia"] },
    {title:"São Tomé and Principe", id:"amphmoLmKBnrkQ7rRrlJ" },
    {title:"Taiwan", id:"VKijrF5RaLV6vgzq3WJp", area:["eastAsia"] },
    {title:"Tajikistan", id:"k1RSq66fxBbFOKiDgyZk" },
    {title:"Tanzania", id:"yrYUaBGL52aOqxdmE3Pz", area:["africa"] },
    {title:"Thailand", id:"MnDQQdlGiucb2eIF9VQj", area:["eastAsia"] },
    {title:"The Gambia", id:"VjHXltnAT3kWRngrgq1S" },
    {title:"Timor-Leste", id:"7gaNbJb2nMoONm1ydyUc" },
    {title:"Togo", id:"DN0nbkzH7JFbJ6pBWz77" },
    {title:"Tonga", id:"JqiEdZLXNAhv7qEl5JT6" },
    {title:"Trinidad and Tobago", id:"v9hIPFTXzPN8J1lVklVw" },
    {title:"Tunisia", id:"75aOFyX0kqSqm8hvvexs" },
    {title:"Turkey", id:"4wEHH7XkR8tg4EzlGVrl" },
    {title:"Turkmenistan", id:"OdhpzFM5hjKVVoi5XLZI" },
    {title:"Turks and Caicos Islands", id:"oSiIzRZE0OOn9IOWFrMc" },
    {title:"Uganda", id:"2e7X1yRlzDvdO6OPpr1W", area:["africa"] },
    {title:"Ukraine", id:"SvsghZ9K9CWbkyFP8eIf" },
    {title:"United Arab Emirates", id:"fwfUrZWgtIUeNldmI92O", area:["westAsia"] },
    {title:"United Kingdom", id:"fci6oSEeX4iBQqvOhD5R", area:["europe"] },
    {title:"United States", id:"wK0fPxpnTOhoODOiPxSB", area:["americas"] },
    {title:"United States Congress", id:"UcRTnaUAUWQuDWoYT0Mv", area:["electoral"] },
    {title:"United States Virgin Islands", id:"hwXDDOH1RvtY5iTuCx5b" },
    {title:"Uruguay", id:"rJUGQ6LPy5nw9R596FMq" },
    {title:"Uzbekistan", id:"cBdXF52l8a2YMj1aGOk8" },
    {title:"Vanuatu", id:"gbHcB0cj91EplbZFeQjy" },
    {title:"Venezuela", id:"wvdGZVJ20RkAkKoJ29WI", area:["americas"] },
    {title:"Vietnam", id:"giArkqe2dBaGnvmPTvoy" },
    {title:"Western Sahara", id:"9c12LZmBu8NrH7BfVJjq" },
    {title:"Yemen", id:"229HRipQzQW6q8mzr418" },
    {title:"Zambia", id:"kBSpzcTZCyHpjrR0ZRmv" },
    {title:"Zimbabwe", id:"uap1a5VzaREXUlv2krAN" },
  ]
  usaStatesMaps = [
    { title:"US Alabama", id:"MHV7I2mAUt1fMgRGv7FZ", area:["xxx"] },
    { title:"US Alaska", id:"FaDntOIhoJ5wGuDUC51h" },
    { title:"US Arizona", id:"7aSJDSRpNUgHfAxU70kC" },
    { title:"US Arkansas", id:"7VMyJYci4cGOXQb4oTOe" },
    { title:"US California", id:"ARwkQ5N6IGcArtuWn83O" },
    { title:"US Colorado", id:"csqZjEzKNazMPw2oNhsj" },
    { title:"US Connecticut", id:"ICPnsOKnYjvFJ8u8Ul2F" },
    { title:"US Delaware", id:"8GpRuS8G306nvBdlxfzY" },
    { title:"US District Of Columbia", id:"Rc4oV9BydSlcsAozYMqF" },
    { title:"US Florida", id:"7jfdnjGyY4F5hB1hMr9T" },
    { title:"US Georgia", id:"biya78AkqOCFWydcos4C" },
    { title:"US Hawaii", id:"71yc26iJ2yVgzGJDDIRe" },
    { title:"US Idaho", id:"dctoLePbqEaryn6MUgUq" },
    { title:"US Illinois", id:"eFHWNxiWWO61tEi3s5hq" },
    { title:"US Indiana", id:"4CCBd4H9OjZTAvZ77X5D" },
    { title:"US Iowa", id:"Qt9bhpf8YXNAXrl4PFbP" },
    { title:"US Kansas", id:"reDWJyZTmnuDECENOM55" },
    { title:"US Kentucky", id:"pM3oF60QECoYO6XkRGE2" },
    { title:"US Louisiana", id:"KTcVZKV5zDe0xlJWVXW3" },
    { title:"US Maine", id:"1SoA2Em2xy2bvsqswyAA" },
    { title:"US Maryland", id:"djqC33Wr2jWdAXHS3poH" },
    { title:"US Massachusetts", id:"Nj7xVV6UwcPLDr7XZmdp" },
    { title:"US Michigan", id:"wIpAuxpN25gmXGm2YWLJ" },
    { title:"US Minnesota", id:"jdgXesyvcPiGv3tUWhH0" },
    { title:"US Mississippi", id:"hhhFPC2iy09Py1XTMAvM" },
    { title:"US Missouri", id:"wRHr6ipAXz4eET05eFZW" },
    { title:"US Montana", id:"dFecEtcaivtSVHeIIYlP" },
    { title:"US Nebraska", id:"bQxywEAblkZr1si8HzUW" },
    { title:"US Nevada", id:"loZa3f2hqUk4SLeL466L" },
    { title:"US New Hampshire", id:"H0Ogqs9ph0nue7VjXnLO" },
    { title:"US New Jersey", id:"YASorGKvlRsd3hZZ8adl" },
    { title:"US New Mexico", id:"N9VKhgg0c20SOZA5YfXX" },
    { title:"US New York", id:"QXns54cKYdSUxr9RLGZi" },
    { title:"US North Carolina", id:"BMVxSo9wOe7wLposlryB" },
    { title:"US North Dakota", id:"otNX6rSB1G66ggn9qHaX" },
    { title:"US Ohio", id:"vtkSDwV4dSc0EdefjWZd" },
    { title:"US Oklahoma", id:"fPcKo8xqqn1MWMNFOIwY" },
    { title:"US Oregon", id:"NcrjFx8HTcEbfX7BVowK" },
    { title:"US Pennsylvania", id:"QaNSA8AAJSxzsm1UwlEA" },
    { title:"US Rhode Island", id:"BhL8HyhpbhLSy6hcp0v2" },
    { title:"US South Carolina", id:"PrvOyQPMnedMtOWzcKFq" },
    { title:"US South Dakota", id:"9K5vbkrtLOw1j9AYsn7l" },
    { title:"US Tennessee", id:"LvFxsSAVhBJB5Wxg6EPN" },
    { title:"US Texas", id:"kXQ1yz5cZy1opa2uTyvf" },
    { title:"US Utah", id:"tbYQz4xpaJgcCUSyMIo1" },
    { title:"US Vermont", id:"JRdEIzKQ1nWk3Ri1ix5Y" },
    { title:"US Virginia", id:"8FmEtBsMKOXCPZdu8mBj" },
    { title:"US Washington", id:"ZGF7IAoiuFUYHnPwpFyp" },
    { title:"US West Virginia", id:"0Wxwjml57L4Yc6FqFPKv" },
    { title:"US Wisconsin", id:"tfLAnWjbwxvhB9MVNNv6" },
    { title:"US Wyoming", id:"scXgwCYMlmC7HOWvvUk1" },
  ]
  indStatesMaps = [
    { title:"Andhra Pradesh", about:"Amaravati", id:"pjqEjDftiqZMYhPSciP5", area:["xxx"] },
    { title:"Arunachal Pradesh", about:"Itanagar", id:"A6befsxlG1MnwGwuJCiJ" },
    { title:"Assam", about:"Dispur", id:"8tbWTph7gexYf9eMszQn" },
    { title:"Bihar", about:"Patna", id:"glokQkpHs3Gcq6YVQ92z" },
    { title:"Chhattisgarh", about:"Raipur", id:"XsYgmHTNt2HkPd6Xvd9S" },
    { title:"Goa", about:"Panaji", id:"qUFKMpC6ZpdAU5440tA9" },
    { title:"Gujarat", about:"Gandhinagar", id:"VZDiWOoiukfo3XetUqB3" },
    { title:"Haryana", about:"Chandigarh", id:"mGAzy5KNEth2qGDUvhBM" },
    { title:"Himachal Pradesh", about:"Shimla", id:"1oxG2tJ72ppnTb46Nm7b" },
    { title:"Jharkhand", about:"Ranchi", id:"NBBKnJN5MXatGwxpPH9u" },
    { title:"Karnataka", about:"Bangalore", id:"1P09TMe8ZZhgGcD24j0M" },
    { title:"Kerala", about:"Thiruvananthapuram", id:"0jk5Uy3OQp11YMmKW8dS" },
    { title:"Madhya Pradesh", about:"Bhopal", id:"N511w7EYv5V46IuMZckm" },
    { title:"Maharashtra", about:"Mumbai", id:"yp9Z5fukBniU3B6eH8aT" },
    { title:"Manipur", about:"Imphal", id:"Cq8KK1P81WiR4Oe1fqic" },
    { title:"Meghalaya", about:"Shillong", id:"bAch38xmIDWSk5sHpEWm" },
    { title:"Mizoram", about:"Aizawl", id:"PK5HFCaGwQJblDH2oOo3" },
    { title:"Nagaland", about:"Kohima", id:"5n2byCCBSAE411jLtBdL" },
    { title:"Odisha", about:"Bhubaneshwar", id:"kAKVCgau1UneShnN5ct6" },
    { title:"Punjab", about:"Chandigarh", id:"bCyiRpTn79qzo8kE4uor" },
    { title:"Rajasthan", about:"Jaipur", id:"9CW5MgC4A2x4zlyLAW9S" },
    { title:"Sikkim", about:"Gangtok", id:"2qbrAXI0VdsXgmqnD0kI" },
    { title:"Tamil Nadu", about:"Chennai", id:"p5PYzXvo1rNxETibELQv" },
    { title:"Telangana", about:"Hyderabad", id:"5hNtI6dESnVpNWmLJzzk" },
    { title:"Tripura", about:"Agartala", id:"4ctyzuLxRj7YobkV5Sw7" },
    { title:"Uttarakhand", about:"Dehradun", id:"7PkNaqVdZl3sa4bx30pR" },
    { title:"Uttar Pradesh", about:"Lucknow", id:"94PvxeiJWYqQhBZTHe2t" },
    { title:"West Bengal", about:"Kolkata", id:"jsWsLpeoQBxFql4QwRRI" },
    { title:"Andaman and Nicobar Islands", about:"Port Blair", id:"MpPQdKEgCtxxCu81mdnj" },
    { title:"Chandigarh", about:"Chandigarh", id:"igVcZoqM4BtLeFJmKcEz" },
    { title:"Dadra & Nagar Haveli and Daman & Diu", about:"Daman", id:"3qptee1PhU4vbZwZSM9F" },
    { title:"The Government of NCT of Delhi", about:"Delhi", id:"1ZBlfLXJklfCjHbVYpaV" },
    { title:"Jammu & Kashmir", about:"Srinagar-S*, Jammu-W*", id:"VbPqjbLQYWM6XlhuDmFh" },
    { title:"Ladakh", about:"Leh", id:"kqS2kcMPVg89qxKrmA9Y" },
    { title:"Lakshadweep Islands", about:"Kavaratti", id:"mB0EhoIDu0x5IDRvNqfu" },
    { title:"Puducherry", about:"Puducherry", id:"KR8QSjFmhvrNAAmXLrAE" },
  ]
  cityMaps = [
    { title:"Tokyo", about:"Japan" , id:"", area:["xxx"] },
    { title:"Delhi", about:"India" , id:"" },
    { title:"Shanghai", about:"China" , id:"" },
    { title:"São Paulo", about:"Brazil" , id:"" },
    { title:"Mexico City", about:"Mexico" , id:"" },
    { title:"Cairo", about:"Egypt" , id:"" },
    { title:"Mumbai", about:"India" , id:"" },
    { title:"Beijing", about:"China" , id:"" },
    { title:"Dhaka", about:"Bangladesh" , id:"" },
    { title:"Osaka", about:"Japan" , id:"" },
    { title:"New York", about:"United States" , id:"" },
    { title:"Karachi", about:"Pakistan" , id:"" },
    { title:"Buenos Aires", about:"Argentina" , id:"", area:["americas"] },
    { title:"Chongqing", about:"China" , id:"" },
    { title:"Istanbul", about:"Turkey" , id:"" },
    { title:"Kolkata", about:"India" , id:"" },
    { title:"Manila", about:"Philippines" , id:"" },
    { title:"Lagos", about:"Nigeria" , id:"" },
    { title:"Rio de Janeiro", about:"Brazil" , id:"" },
    { title:"Tianjin", about:"China" , id:"" },
  ]
  otherMaps = [
    { title:"Tibet", id:"eknk2qZgvRquCwIyZO9W", area:["xxx"] },
    { title:"Kurdistan", id:"3B20yfhZwuD8xeAimeeF" },
    /*
    { title:"Quebec", id:"" },
    { title:"East Turkestan", id:"" },
    { title:"Macau", id:"" },
    { title:"Manchukuo", id:"" },
    { title:"Balochistan", id:"" },
    { title:"Aryavrata", id:"" },
    { title:"Bharatvarsh", id:"" },
    { title:"Greater India", id:"" },
    { title:"Maratha Empire", id:"" },
    { title:"Chola Empire", id:"" },
    { title:"British India", id:"" },
    { title:"Kushan Empire", id:"" },
    { title:"Mauryan Empire", id:"" },
    { title:"Gupta Empire", id:"" },
    { title:"Mughal Empire", id:"" },
    { title:"USSR", id:"" },
    { title:"Russian Empire", id:"" },
    { title:"Mongol Empire", id:"" },
    { title:"Qing dynasty", id:"" },
    { title:"Spanish Empire", id:"" },
    { title:"Empire of Japan", id:"" },
    { title:"Iberian Union", id:"" },
    { title:"Second French colonial empire", id:"" },
    { title:"Abbasid Caliphate", id:"" },
    { title:"Umayyad Caliphate", id:"" },
    { title:"Yuan dynasty", id:"" },
    { title:"Ottoman Empire", id:"" },
    { title:"Roman Empire", id:"" },
    */
  ]

  
  constructor(
    public router: Router,
    public clipboard: Clipboard
  ) { }

  get getHeight(){
    return window.innerHeight;
  }
  get getWidth(){
    return window.innerWidth;
  }
  
  testName(name:string){
    const newKey  = new FormControl(name, [
      Validators.pattern('^[0-9A-Za-z ]+$')
    ]);
    return newKey.invalid;
  }

  testPhone(phone:string){
    const newNum  = new FormControl(phone, [
      Validators.pattern('^[0-9]+$')
    ]);
    return newNum.invalid;
  }

  testEmail(email:string){
    const newMail  = new FormControl(email, [
      Validators.pattern('^[a-zA-Z0-9.!#$%&’*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$')
    ]);
    return newMail.invalid;
  }

  testPass(pass:string){
    const newKey  = new FormControl(pass, [
      Validators.pattern('^[0-9A-Za-z@]+$')
    ]);
    return newKey.invalid;
  }

  copyCLIPBOARD(x:any){
    this.clipboard.copy(x);
  }


}
